#! /bin/bash

echo "¿QUÉ QUIERE CONSULTAR?"
echo
echo "1) BUSCAR USUARIO"
echo "2) NÓMINA DE ASESORES PROFESIONALES"
echo "3) NÓMINA DE ADMINISTRATIVOS"
echo "4) NÓMINA DE GERENTES DE SUCURSAL"
echo "5) GERENTE GENERAL"
read op

	case $op in
	1)
read -p "INGRESE EL NOMBRE DEL USUARIO A BUSCAR: " NOM

f=$(grep "$NOM" /etc/passwd | wc -l)

if [ $f -eq 0 ]; then
echo "EL USUARIO NO EXISTE."
else
echo
grep "$NOM" /etc/passwd | cut -d ":" -f 1,3
fi
	;;
	2)
echo
grep 1000 /etc/passwd | cut -d ":" -f 1
	;;
	3)
echo
grep 1001 /etc/passwd | cut -d ":" -f 1
	;;
	4)
echo
grep 1002 /etc/passwd | cut -d ":" -f 1
	;;
	5)
echo
grep 1003 /etc/passwd | cut -d ":" -f 1
esac
