#! /bin/bash

buscarUsuario(){
	read -p "Buscar: " busqueda
	grep "$busqueda" /etc/passwd | cut -d ":" -f 1,3
}

listarUsuarios(){
	grep "$1" /etc/passwd | cut -d ":" -f 1
}


while :
do
	echo "- Consulta de Usuarios"
	echo "1) Buscar"
	echo "2) Listado de Asesores"
	echo "3) Listado de Administrativos"
	echo "4) Listado de Gerentes"

	read -p "Ingrese una opción: " opc

	case $opc in 
		1) buscarUsuario;;	
		2) listarUsuarios 1000;;
		3) listarUsuarios 1001;;
		4) listarUsuarios 1002;;
		*) echo "Opción incorrecta";;
	esac

done