#! /bin/bash

while :
do
	read -p "Nombre del usuario a eliminar: " nombre

	# Buscar usuario
	usuario=$(grep "$nombre" /etc/passwd | wc -l)

	if [ "$usuario" -eq 1 ]; then
        read -p "Seguro que desea eliminar al usuario $nombre ¿Confirmar [S]?" confirmado
        if [ $confirmado == "S" ]; then
            deluser "$nombre"
            echo "Usuario eliminado exitosamente"
        else
            echo "Acción cancelada"
        fi
	else
        echo "El usuario $nombre no existe, intente nuevamente"
	fi
done