#! /bin/bash
clear

while :
do
	echo
	echo '======== S.I.GES.VI ========'
	echo
	echo '------ Menú Principal ------'
	echo '1) Menú usuarios'
	echo '2) Menú operador de cómputos'
	echo '0) Salir'
	echo
	read -p 'Ingrese una opción: ' opc

	case $opc in
	'1') sh usuarios;;
	'2') echo 'Opción sin implementar...';;
	'0') exit 0;;
	*) echo 'Opción incorrecta, intente nuevamente';;
	esac
done
