#! /bin/bash
# Si se modifica el nombre del grupo habría que actualizar script
# - Comprobar que exista el grupo antes de crear el usuario
# - Verificar que no se pueda agregar el usuario si no existe el grupo
# Pasar a funciones
# Nota: Capaz que convendría eliminar el usuario y agregarlo denuevo para asi poder ingresar el nuevo grupo o buscar otra forma

while :
do
	read -p "Nombre del usuario: " nombreActual

	# Buscar usuario
	usuario=$(grep "$nombreActual" /etc/passwd | wc -l)

	# Si el usuario no existe salgo del while
	if [ "$usuario" -eq 0 ]; then
		echo "El usuario $nombreActual no existe, intente nuevamente"
	else
		break
	fi
done

while :
do
	read -p "Nuevo nombre: " nombreNuevo

	# Buscar usuario
	usuario=$(grep "$nombreNuevo" /etc/passwd | wc -l)

	# Si el nuevo nombre ya existe salgo del while
	if [ "$usuario" -eq 1 && "$nombreNuevo" != "$nombreActual" ]; then
		echo "El nombre de usuario $nombreNuevo ya existe, ingrese otro nombre"
	else
		break
	fi
done

PS2="Ingrese el nuevo grupo: "
select grupoNuevo in "Asesor_Profesional" "Administrativo" "Gerente_Sucursal" "Gerente_General";
do
	case $grupoNuevo in
		*) echo "Opción incorrecta";;
	esac
done

if [$grupoNuevo == "Gerente_General"]; then
	# Comprueba si existe el Gerente General
	existeGG= $(grep 1003 /etc/passwd | wc -l) -eq 1
	if [ existeGG ]; then
		echo "Ya existe en el sistema un Gerente General"
	else
fi

if [!existeGG]; then
	read -p "Se modificará el usuario $nombreActual al grupo $grupo. ¿Confirmar[S]?:" confirmado
	echo "Se modificará el usuario $nombreActual con los siguientes datos:"
	read -p "$nombreNuevo, $grupoNuevo ¿Confirmar[S]?" confirmado
	if [$confirmado == "S"]; then
		usermod -l "$nombreNuevo" "$NombreActual"
	fi
fi