#! /bin/bash

clear
while :
do
	echo
	echo "======== S.I.GES.VI ========"
	echo
	echo "------ Menú Usuarios ------"
	echo "1) Agregar"
	echo "2) Eliminar"
	echo "3) Modificar"
	echo "4) Consultar"
	echo "0) Volver"
	echo
	read -p "Ingrese una opción: " opc
	case $opc in
	"1") ./registro;;
	"2") sh eliminar;;
	"3") sh modificar;;
	"4") sh consulta;;
	"0") break;;
	*) echo "Opción incorrecta, intente nuevamente";;
	esac
done
